In [3]:
import numpy as np

### grid:

1x  |  xx  |  xx  |  xx  |  xx \
xx  |  9x  |  x3  |  xx  |  xx \
xx  |  xx  |  xx  |  x4  |  x5 

10x  |  x80   |  xx   |  xx   |  xx \
xx   |  xx  |  x30  |  xx   |  xx \
xx   |  xx   |  xx   |  x40  |  x50 

In [147]:
hsamp = np.array([[[[[1,10],[0,80],[0,6],[0,6],[0,6]],
                [[0,6],[9,6],[0,6],[0,6],[0,6]],
                [[0,6],[0,6],[0,6],[0,6],[0,6]]]],

                [[[[0,6],[0,6],[0,6],[0,6],[0,6]],
                [[0,6],[0,6],[3,30],[0,6],[0,6]],
                [[0,6],[0,6],[0,6],[4,40],[5,50]]]]])
print(hsamp.shape)
# print(grid)
hsone=hsamp[...,0]
print(hsone.shape)

(2, 1, 3, 5, 2)
(2, 1, 3, 5)


In [148]:
hsamp2 = np.repeat(hsone[...,np.newaxis], 2, axis=4)
print(hsamp2.shape)

(2, 1, 3, 5, 2)


In [5]:
hsmax = np.amax(hsamp, axis=(0,1,2))

In [6]:
print(hsmax)

[[ 1 10]
 [ 9 80]
 [ 3 30]
 [ 4 40]
 [ 5 50]]


In [7]:
# one real
hsmax = np.amax(hsone, axis=(0,1,2))
shape = hsone.shape
print(shape)
newshape = (shape[0]*shape[1]*shape[2], shape[3])
print(newshape)
hsone = hsone.reshape(newshape) # change hsamp to shape (M-1*Q-1*Z-1, F-1)
argmax = np.argmax(hsone, axis=0) # max at each frequency & realization
hsone = hsone.reshape(shape) # restore hsamp shape to (M-1, Q-1, Z-1, F-1)
print(hsone.shape)
mqz = np.array(np.unravel_index(argmax, shape[:-1])) # unravel indices
print('mqz', mqz.shape)
print(mqz)
f_ids = np.linspace(0,len(mqz[0])-1,len(mqz[0])).astype(int) # frequency indices
print(np.append(mqz, f_ids))
ssnew = np.append(mqz, f_ids).reshape(4,len(f_ids))
print('ssnew', ssnew)
# print(hsone[ssnew[0], ssnew[1], ssnew[2], ssnew[3]])

(2, 1, 3, 5)
(6, 5)
(2, 1, 3, 5)
mqz (3, 5)
[[0 0 1 1 1]
 [0 0 0 0 0]
 [0 1 1 2 2]]
[0 0 1 1 1 0 0 0 0 0 0 1 1 2 2 0 1 2 3 4]
ssnew [[0 0 1 1 1]
 [0 0 0 0 0]
 [0 1 1 2 2]
 [0 1 2 3 4]]


In [139]:
#hsamp for all bins at all realizations

#gets max for each frequency and realization
max = np.amax(hsamp, axis=(0,1,2))
print(max)
shape = hsamp.shape
print('shape',shape)
newshape = (shape[0]*shape[1]*shape[2], shape[3], shape[4])
print('newshape', newshape)
hsamp = hsamp.reshape(newshape)
argmax = np.argmax(hsamp, axis=0)
hsamp = hsamp.reshape(shape)

# shape (3, F, R)
mqz = np.array(np.unravel_index(argmax, shape[:-2])) # unravel indices
print('mqz', mqz.shape)


# I GOt IT!!!!!
# MQZ in shape (3,F,R)
# Want to get MQZF in shape (4,F,R)
# Need f_ids in shape (1,F,R) to append

f_ids = np.linspace(0,len(mqz[0])-1,len(mqz[0])).astype(int) # frequency indices
f_ids = np.repeat(f_ids, R).reshape(F,R)[np.newaxis,:]
ssnew = np.append(mqz,f_ids, axis=0)
print(ssnew.shape)

[[ 1 10]
 [ 9 80]
 [ 3 30]
 [ 4 40]
 [ 5 50]]
shape (2, 1, 3, 5, 2)
newshape (6, 5, 2)
mqz (3, 5, 2)
(4, 5, 2)


In [28]:
# print(mqz.shape, mqz)
one = mqz[:,:,0]
print(one.shape)
one = np.append(one, f_ids)
print(one.reshape(5,4))
print(mqz.shape)
# aaa = mqz.reshape(2*1*3*5,2)
# print(aaa)

for r in range(2):
    new = np.append(mqz[:,:,r], f_ids).reshape(5,4)
    print('new', new.shape, new)
    mqz[:,:,r] = new

(3, 5)
[[0 0 1 1]
 [1 0 0 0]
 [0 0 0 1]
 [1 2 2 0]
 [1 2 3 4]]
(3, 5, 2)
new (5, 4) [[0 0 1 1]
 [1 0 0 0]
 [0 0 0 1]
 [1 2 2 0]
 [1 2 3 4]]


ValueError: could not broadcast input array from shape (5,4) into shape (3,5)

In [9]:
print(mqz.shape)
doublef = np.array([[0,0],[1,1],[2,2],[3,3],[4,4]])
print(doublef.shape)
print(f_ids.shape)
print(np.append(mqz,doublef, axis=1))

(3, 5, 2)
(5, 2)
(5,)


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 3 dimension(s) and the array at index 1 has 2 dimension(s)

In [29]:
for r in range(shape[4]):
    print(r)
    for f in range(shape[3]):
        print(mqz[:,f,r].shape)
        # mqz[0,f,r]
        # mqz[f,r] = np.append(mqz[:,f,r], f)

0
(3,)
(3,)
(3,)
(3,)
(3,)
1
(3,)
(3,)
(3,)
(3,)
(3,)


In [64]:
arr = np.array([[[1,1], [2,2], [3,3]]])
print(arr, arr.shape)
app = np.array([[[0], [5], [6]]])
print(app, app.shape)
res = np.append(arr, app, axis=2)
print(res, res.shape)

# take shape (a,b,c) and append shape (a,b,d) to get shape (a,b,c+d)

[[[1 1]
  [2 2]
  [3 3]]] (1, 3, 2)
[[[0]
  [5]
  [6]]] (1, 3, 1)
[[[1 1 0]
  [2 2 5]
  [3 3 6]]] (1, 3, 3)


In [81]:
arr = np.array([[1],[2],[3]])
print(arr, arr.shape)
app = np.array([[0],[0],[3]])
print(app, app.shape)
res = np.append(arr, app, axis=1)
print(res, res.shape)

# take shape (a,b,c) and append shape (a,b,d) to get shape (a,b,c+d)
# I have shape (3,5,2) and I want to append ..... 
# to get shape (4,5,2)

[[1]
 [2]
 [3]] (3, 1)
[[0]
 [0]
 [3]] (3, 1)
[[1 0]
 [2 0]
 [3 3]] (3, 2)


In [89]:
arr = np.array([[1,2],[3,4]])
print(arr, arr.shape)
app = np.array([[0,0]])
print(app, app.shape)
res = np.append(arr, app, axis=0)
print(res, res.shape)

# take shape (a,b,c) and append shape (a,b,d) to get shape (a,b,c+d)
# I have shape (3,5,2) and I want to append ..... 
# to get shape (4,5,2)

[[1 2]
 [3 4]] (2, 2)
[[0 0]] (1, 2)
[[1 2]
 [3 4]
 [0 0]] (3, 2)


In [86]:
arr = np.array([[1,2],[3,4]])
print(arr, arr.shape)
app = np.array([[0],[0]])
print(app, app.shape)
res = np.append(arr, app, axis=1)
print(res, res.shape)

# take shape (a,b,c) and append shape (a,b,d) to get shape (a,b,c+d)
# I have shape (3,5,2) and I want to append ..... 
# to get shape (4,5,2)

[[1 2]
 [3 4]] (2, 2)
[[0]
 [0]] (2, 1)
[[1 2 0]
 [3 4 0]] (2, 3)


In [101]:
arr = np.array([[[1],[2]],[[3],[4]],[[5],[6]]])
print(arr, arr.shape)
app = np.array([[[0],[0]]])
print(app, app.shape)
res = np.append(arr, app, axis=0)
print(res, res.shape)

# take shape (a,b,c) and append shape (a,b,d) to get shape (a,b,c+d)
# I have shape (3,5,2) and I want to append ..... 
# to get shape (4,5,2)

[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]] (3, 2, 1)
[[[0]
  [0]]] (1, 2, 1)
[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]

 [[0]
  [0]]] (4, 2, 1)


In [127]:
print(mqz.shape) # mqz is shape (3,5,2) = (3,F,R)
# I want to append frequencies to get shape (4,5,2) = (4,F,R)
# this means I need my f_indices in shape (1,5,2)
print(f_ids.shape)
print(f_ids[np.newaxis,:,np.newaxis].shape)
print(np.tile(f_ids, (1,2)))
print(np.repeat(f_ids, 2).reshape(5,2).shape)

(3, 5, 2)
(5,)
(1, 5, 1)
[[0 1 2 3 4 0 1 2 3 4]]
(5, 2)


In [131]:
R = 2
F = 5
reps = np.repeat(f_ids, R).reshape(F,R)
resh = reps[np.newaxis,:]
print(resh)
print(resh.shape)

[[[0 0]
  [1 1]
  [2 2]
  [3 3]
  [4 4]]]
(1, 5, 2)


In [133]:
print(np.append(mqz, resh, axis=0).shape)

(4, 5, 2)


In [136]:
# I GOt IT!!!!!
# MQZ in shape (3,F,R)
# Want to get MQZF in shape (4,F,R)
# Need f_ids in shape (1,F,R) to append

f_ids = np.linspace(0,len(mqz[0])-1,len(mqz[0])).astype(int) # frequency indices
f_ids = np.repeat(f_ids, R).reshape(F,R)[np.newaxis,:]
mqzf = np.append(mqz,f_ids, axis=0)
print(mqzf.shape)

(4, 5, 2)


In [142]:
print(ssnew[0].shape)

(5, 2)
